general:
  meteocat_api_key: "ksajclksajclaskjwo32cmsdsmadlqwlkewq単l"
  meteocat_codi_estacio: ""
  meteocat_codi_variable: ""
database:
  influx_server: "localhost"
  influx_port: "8086"
  influx_bucket: "meteocat-testing"
  influx_measurement: "meteocat_all_by_station"
  influx_org: "Testing"
  influx_token: "5dYxum3y8db1ZZ4uCYkEjpt4C0Ascas単lckas単lcaks単clsakMDv9GJewEHiLF6FjCQnqTDjrS-90ZLwFCLQBg=="


