general:
  meteocat_api_key: "API_KEY"
database:
  influx_server: "localhost"
  influx_port: "8086"
  influx_bucket: "meteocat-testing"
  influx_measurement: "meteocat_all_by_station"
  influx_org: "Testing"
  influx_username: ""
  influx_password: ""
  influx_token: "random"


